spring:
  jpa:
    database-platform: com.xxl.job.admin.config.db.MySQLInnoDBDialect
    show-sql: false
    properties:
      hibernate:
        #在没有事务的情况下允许懒加载
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.xxl.job.admin.config.JpaPhysicalNamingStrategy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
      validation-timeout: 1000
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.0.0.233:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root


  mvc:
    pathmatch:
        # 配置策略
        matching-strategy: ANT_PATH_MATCHER

xxl:
  job:
    notify:
      feishu:
        enabled: true
        secret: YZp84h85w3rYL7X2R2ly0g
        # hook地址
        webhookUrl: 'https://open.feishu.cn/open-apis/bot/v2/hook/48b79606-ca5b-4ab7-beee-11009d6c94fb'
        # 需要发送的文本信息
        message: "任务：#{event.task.description} \n作者：#{event.task.author} \n客户端实例地址：#{event.log.instanceUrl} \n调度状态：#{event.log.triggerStatus} \n执行状态：#{event.log.handleStatus}"
        #message: "客户端实例地址：#{event.log.instanceUrl} \n调度状态：#{event.log.triggerStatus} \n执行状态：#{event.log.handleStatus}"
    accessToken: default_token
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
